import { Ban } from "./Ban";
import { Channel } from "./Channel";
import { Emoji } from "./Emoji";
import { Invite } from "./Invite";
import { Member } from "./Member";
import { Role } from "./Role";
import { Sticker } from "./Sticker";
import { Template } from "./Template";
import { User } from "./User";
import { VoiceState } from "./VoiceState";
import { Webhook } from "./Webhook";
export interface Guild {
  id: string;
  afk_channel_id?: string;
  afk_channel?: Channel;
  afk_timeout?: number;
  bans: Ban[];
  banner?: string;
  default_message_notifications?: number;
  description?: string;
  discovery_splash?: string;
  explicit_content_filter?: number;
  features: string[];
  primary_category_id?: string;
  icon?: string;
  large?: boolean;
  max_members?: number;
  max_presences?: number;
  max_video_channel_users?: number;
  member_count?: number;
  presence_count?: number;
  members: Member[];
  roles: Role[];
  channels: Channel[];
  template_id?: string;
  template: Template;
  emojis: Emoji[];
  stickers: Sticker[];
  invites: Invite[];
  voice_states: VoiceState[];
  webhooks: Webhook[];
  mfa_level?: number;
  name: string;
  owner_id?: string;
  owner?: User;
  preferred_locale?: string;
  premium_subscription_count?: number;
  premium_tier?: number;
  public_updates_channel_id: string;
  public_updates_channel?: Channel;
  rules_channel_id?: string;
  rules_channel?: string;
  region?: string;
  splash?: string;
  system_channel_id?: string;
  system_channel?: Channel;
  system_channel_flags?: number;
  unavailable: boolean;
  verification_level?: number;
  welcome_screen: {
    enabled: boolean;
    description: string;
    welcome_channels: {
      description: string;
      emoji_id?: string;
      emoji_name?: string;
      channel_id: string;
    }[];
  };
  widget_channel_id?: string;
  widget_channel?: Channel;
  widget_enabled: boolean;
  nsfw_level?: number;
  nsfw: boolean;
  parent?: string;
  // only for developer portal
  permissions?: number;
  premium_progress_bar_enabled: boolean;
}
